version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_web
    volumes:
      - ./:/var/www/html
      - ./apache/000-default.conf:/etc/apache2/sites-available/000-default.conf
    ports:
      - "8000:80"
    depends_on:
      - db
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=laravel
      - DB_USERNAME=root
      - DB_PASSWORD=root
    networks:
      - app-network

  db:
    image: mysql:5.7
    restart: always
    ports:
      - "3308:3306"
    environment:
      MYSQL_DATABASE: 'laravel'
      MYSQL_ROOT_PASSWORD: 'root'
    volumes:
      - ./db:/var/lib/mysql
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
    driver: bridge
